# Generated by Django 4.2.7 on 2023-12-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontable',
            name='collection_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='back',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='front',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topictable',
            name='topic_name',
            field=models.CharField(max_length=50),
        ),
    ]
