# Generated by Django 4.2.2 on 2023-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topictable',
            old_name='topicname',
            new_name='topic_name',
        ),
        migrations.AlterField(
            model_name='collectiontable',
            name='topics',
            field=models.ManyToManyField(blank=True, through='api.CollectionTopic', to='api.topictable'),
        ),
    ]
