# Generated by Django 4.2.7 on 2023-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_collectiontable_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='back',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='front',
            field=models.CharField(max_length=200),
        ),
    ]
